package com.projetIF4.model;

//Generated 29 mars 2014 16:50:57 by Hibernate Tools 3.6.0

/**
 * ChoixProjet generated by hbm2java
 */
public class ChoixProjet implements java.io.Serializable {
    private ChoixProjetId id;
    private Projetpropose projetpropose;
    private Etudiant      etudiantByCinetud2;
    private Etudiant      etudiantByCinetud1;
    private int           numChoix;

    /**
     *
     */
    public ChoixProjet() {}

    /**
     *
     * @param id
     * @param projetpropose
     * @param etudiantByCinetud1
     * @param numChoix
     */
    public ChoixProjet(ChoixProjetId id, Projetpropose projetpropose, Etudiant etudiantByCinetud1, int numChoix) {
        this.id                 = id;
        this.projetpropose      = projetpropose;
        this.etudiantByCinetud1 = etudiantByCinetud1;
        this.numChoix           = numChoix;
    }

    /**
     *
     * @param id
     * @param projetpropose
     * @param etudiantByCinetud2
     * @param etudiantByCinetud1
     * @param numChoix
     */
    public ChoixProjet(ChoixProjetId id, Projetpropose projetpropose, Etudiant etudiantByCinetud2,
                       Etudiant etudiantByCinetud1, int numChoix) {
        this.id                 = id;
        this.projetpropose      = projetpropose;
        this.etudiantByCinetud2 = etudiantByCinetud2;
        this.etudiantByCinetud1 = etudiantByCinetud1;
        this.numChoix           = numChoix;
    }

    /**
     *
     * @return
     */
    public ChoixProjetId getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(ChoixProjetId id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public Projetpropose getProjetpropose() {
        return this.projetpropose;
    }

    /**
     *
     * @param projetpropose
     */
    public void setProjetpropose(Projetpropose projetpropose) {
        this.projetpropose = projetpropose;
    }

    /**
     *
     * @return
     */
    public Etudiant getEtudiantByCinetud2() {
        return this.etudiantByCinetud2;
    }

    /**
     *
     * @param etudiantByCinetud2
     */
    public void setEtudiantByCinetud2(Etudiant etudiantByCinetud2) {
        this.etudiantByCinetud2 = etudiantByCinetud2;
    }

    /**
     *
     * @return
     */
    public Etudiant getEtudiantByCinetud1() {
        return this.etudiantByCinetud1;
    }

    /**
     *
     * @param etudiantByCinetud1
     */
    public void setEtudiantByCinetud1(Etudiant etudiantByCinetud1) {
        this.etudiantByCinetud1 = etudiantByCinetud1;
    }

    /**
     *
     * @return
     */
    public int getNumChoix() {
        return this.numChoix;
    }

    /**
     *
     * @param numChoix
     */
    public void setNumChoix(int numChoix) {
        this.numChoix = numChoix;
    }

    @Override
    public int hashCode() {
        int hash = 5;

        hash = 17 * hash + this.numChoix;

        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        if (getClass() != obj.getClass()) {
            return false;
        }

        final ChoixProjet other = (ChoixProjet) obj;

        if (this.numChoix != other.numChoix) {
            return false;
        }

        return true;
    }
}



