package com.projetIF4.model;

//Generated 29 mars 2014 16:50:57 by Hibernate Tools 3.6.0

//~--- JDK imports ------------------------------------------------------------

import javax.faces.bean.ManagedBean;

/**
 * ChoixEnseignantId generated by hbm2java
 */
@ManagedBean
public class ChoixEnseignantId implements java.io.Serializable {
    private int cinEnseignant;
    private int cinetu;

    /**
     *
     */
    public ChoixEnseignantId() {}

    /**
     *
     * @param cinEnseignant
     * @param cinetu
     */
    public ChoixEnseignantId(int cinEnseignant, int cinetu) {
        this.cinEnseignant = cinEnseignant;
        this.cinetu        = cinetu;
    }

    /**
     *
     * @return
     */
    public int getCinEnseignant() {
        return this.cinEnseignant;
    }

    /**
     *
     * @param cinEnseignant
     */
    public void setCinEnseignant(int cinEnseignant) {
        this.cinEnseignant = cinEnseignant;
    }

    /**
     *
     * @return
     */
    public int getCinetu() {
        return this.cinetu;
    }

    /**
     *
     * @param cinetu
     */
    public void setCinetu(int cinetu) {
        this.cinetu = cinetu;
    }

    @Override
    public int hashCode() {
        int hash = 7;

        hash = 13 * hash + this.cinEnseignant;
        hash = 13 * hash + this.cinetu;

        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        if (getClass() != obj.getClass()) {
            return false;
        }

        final ChoixEnseignantId other = (ChoixEnseignantId) obj;

        if (this.cinEnseignant != other.cinEnseignant) {
            return false;
        }

        if (this.cinetu != other.cinetu) {
            return false;
        }

        return true;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
