package com.projetIF4.model;

//Generated 29 mars 2014 16:50:57 by Hibernate Tools 3.6.0

/**
 * ChoixEnseignant generated by hbm2java
 */
public class ChoixEnseignant implements java.io.Serializable {
    private ChoixEnseignantId id;
    private Etudiant          etudiantByCinetu;
    private Etudiant          etudiantByCinetu2;
    private Enseignant        enseignant;
    private int               numChoix;

    /**
     *
     */
    public ChoixEnseignant() {}

    /**
     *
     * @param id
     * @param etudiantByCinetu
     * @param enseignant
     * @param numChoix
     */
    public ChoixEnseignant(ChoixEnseignantId id, Etudiant etudiantByCinetu, Enseignant enseignant, int numChoix) {
        this.id               = id;
        this.etudiantByCinetu = etudiantByCinetu;
        this.enseignant       = enseignant;
        this.numChoix         = numChoix;
    }

    /**
     *
     * @param id
     * @param etudiantByCinetu
     * @param etudiantByCinetu2
     * @param enseignant
     * @param numChoix
     */
    public ChoixEnseignant(ChoixEnseignantId id, Etudiant etudiantByCinetu, Etudiant etudiantByCinetu2,
                           Enseignant enseignant, int numChoix) {
        this.id                = id;
        this.etudiantByCinetu  = etudiantByCinetu;
        this.etudiantByCinetu2 = etudiantByCinetu2;
        this.enseignant        = enseignant;
        this.numChoix          = numChoix;
    }

    /**
     *
     * @return
     */
    public ChoixEnseignantId getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(ChoixEnseignantId id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public Etudiant getEtudiantByCinetu() {
        return this.etudiantByCinetu;
    }

    /**
     *
     * @param etudiantByCinetu
     */
    public void setEtudiantByCinetu(Etudiant etudiantByCinetu) {
        this.etudiantByCinetu = etudiantByCinetu;
    }

    /**
     *
     * @return
     */
    public Etudiant getEtudiantByCinetu2() {
        return this.etudiantByCinetu2;
    }

    /**
     *
     * @param etudiantByCinetu2
     */
    public void setEtudiantByCinetu2(Etudiant etudiantByCinetu2) {
        this.etudiantByCinetu2 = etudiantByCinetu2;
    }

    /**
     *
     * @return
     */
    public Enseignant getEnseignant() {
        return this.enseignant;
    }

    /**
     *
     * @param enseignant
     */
    public void setEnseignant(Enseignant enseignant) {
        this.enseignant = enseignant;
    }

    /**
     *
     * @return
     */
    public int getNumChoix() {
        return this.numChoix;
    }

    /**
     *
     * @param numChoix
     */
    public void setNumChoix(int numChoix) {
        this.numChoix = numChoix;
    }

    @Override
    public int hashCode() {
        int hash = 3;

        hash = 29 * hash + this.numChoix;

        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        if (getClass() != obj.getClass()) {
            return false;
        }

        final ChoixEnseignant other = (ChoixEnseignant) obj;

        if (this.numChoix != other.numChoix) {
            return false;
        }

        return true;
    }
}



