package com.projetIF4.model;

//Generated 24 mars 2014 18:11:52 by Hibernate Tools 3.6.0

//~--- non-JDK imports --------------------------------------------------------

import com.projetIF4.hibernate.HibernateUtil;

import org.hibernate.Session;
import org.hibernate.Transaction;

//~--- JDK imports ------------------------------------------------------------

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Enseignant generated by hbm2java
 */
public class Enseignant implements java.io.Serializable {
    private Set     choixEnseignants = new HashSet(0);
    private Set     pfas             = new HashSet(0);
    private Set     pfesForEnsCin2   = new HashSet(0);
    private Set     pfesForEnsCin1   = new HashSet(0);
    private Set     projetproposes   = new HashSet(0);
    private Set     pfesForEnsCin    = new HashSet(0);
    private int     cinEnseignant;
    private Grade   grade;
    private String  nom;
    private String  prenom;
    private String  mail;
    private Integer tel;

    /**
     *
     */
    public Enseignant() {
        grade = new Grade();
    }

    /**
     *
     * @param cinEnseignant
     * @param grade
     * @param mail
     */
    public Enseignant(int cinEnseignant, Grade grade, String mail) {
        this.cinEnseignant = cinEnseignant;
        this.grade         = grade;
        this.mail          = mail;
    }

    /**
     *
     * @param cinEnseignant
     * @param grade
     * @param nom
     * @param prenom
     * @param mail
     * @param tel
     * @param choixEnseignants
     * @param pfas
     * @param pfesForEnsCin2
     * @param pfesForEnsCin1
     * @param projetproposes
     * @param pfesForEnsCin
     */
    public Enseignant(int cinEnseignant, Grade grade, String nom, String prenom, String mail, Integer tel,
                      Set choixEnseignants, Set pfas, Set pfesForEnsCin2, Set pfesForEnsCin1, Set projetproposes,
                      Set pfesForEnsCin) {
        this.cinEnseignant    = cinEnseignant;
        this.grade            = grade;
        this.nom              = nom;
        this.prenom           = prenom;
        this.mail             = mail;
        this.tel              = tel;
        this.choixEnseignants = choixEnseignants;
        this.pfas             = pfas;
        this.pfesForEnsCin2   = pfesForEnsCin2;
        this.pfesForEnsCin1   = pfesForEnsCin1;
        this.projetproposes   = projetproposes;
        this.pfesForEnsCin    = pfesForEnsCin;
    }

    /**
     *
     * @return
     */
    public int getCinEnseignant() {
        return this.cinEnseignant;
    }

    /**
     *
     * @param cinEnseignant
     */
    public void setCinEnseignant(int cinEnseignant) {
        this.cinEnseignant = cinEnseignant;
    }

    /**
     *
     * @return
     */
    public Grade getGrade() {
        return this.grade;
    }

    /**
     *
     * @param grade
     */
    public void setGrade(Grade grade) {
        this.grade = grade;
    }

    /**
     *
     * @return
     */
    public String getNom() {
        return this.nom;
    }

    /**
     *
     * @param nom
     */
    public void setNom(String nom) {
        this.nom = nom;
    }

    /**
     *
     * @return
     */
    public String getPrenom() {
        return this.prenom;
    }

    /**
     *
     * @param prenom
     */
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    /**
     *
     * @return
     */
    public String getMail() {
        return this.mail;
    }

    /**
     *
     * @param mail
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     *
     * @return
     */
    public Integer getTel() {
        return this.tel;
    }

    /**
     *
     * @param tel
     */
    public void setTel(Integer tel) {
        this.tel = tel;
    }

    /**
     *
     * @return
     */
    public Set getChoixEnseignants() {
        return this.choixEnseignants;
    }

    /**
     *
     * @param choixEnseignants
     */
    public void setChoixEnseignants(Set choixEnseignants) {
        this.choixEnseignants = choixEnseignants;
    }

    /**
     *
     * @return
     */
    public Set getPfas() {
        return this.pfas;
    }

    /**
     *
     * @param pfas
     */
    public void setPfas(Set pfas) {
        this.pfas = pfas;
    }

    /**
     *
     * @return
     */
    public Set getPfesForEnsCin2() {
        return this.pfesForEnsCin2;
    }

    /**
     *
     * @param pfesForEnsCin2
     */
    public void setPfesForEnsCin2(Set pfesForEnsCin2) {
        this.pfesForEnsCin2 = pfesForEnsCin2;
    }

    /**
     *
     * @return
     */
    public Set getPfesForEnsCin1() {
        return this.pfesForEnsCin1;
    }

    /**
     *
     * @param pfesForEnsCin1
     */
    public void setPfesForEnsCin1(Set pfesForEnsCin1) {
        this.pfesForEnsCin1 = pfesForEnsCin1;
    }

    /**
     *
     * @return
     */
    public Set getProjetproposes() {
        return this.projetproposes;
    }

    /**
     *
     * @param projetproposes
     */
    public void setProjetproposes(Set projetproposes) {
        this.projetproposes = projetproposes;
    }

    /**
     *
     * @return
     */
    public Set getPfesForEnsCin() {
        return this.pfesForEnsCin;
    }

    /**
     *
     * @param pfesForEnsCin
     */
    public void setPfesForEnsCin(Set pfesForEnsCin) {
        this.pfesForEnsCin = pfesForEnsCin;
    }

    @Override
    public int hashCode() {
        int hash = 5;

        hash = 23 * hash + this.cinEnseignant;
        hash = 23 * hash + Objects.hashCode(this.nom);
        hash = 23 * hash + Objects.hashCode(this.prenom);
        hash = 23 * hash + Objects.hashCode(this.mail);
        hash = 23 * hash + Objects.hashCode(this.tel);

        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        if (getClass() != obj.getClass()) {
            return false;
        }

        final Enseignant other = (Enseignant) obj;

        if (this.cinEnseignant != other.cinEnseignant) {
            return false;
        }

        if (!Objects.equals(this.nom, other.nom)) {
            return false;
        }

        if (!Objects.equals(this.prenom, other.prenom)) {
            return false;
        }

        if (!Objects.equals(this.mail, other.mail)) {
            return false;
        }

        if (!Objects.equals(this.tel, other.tel)) {
            return false;
        }

        return true;
    }

    /**
     *
     * @return
     * @throws Exception
     */
    public boolean save() throws Exception {
        final Session session = HibernateUtil.currentSession();

        try {
            final Transaction transaction = session.beginTransaction();

            try {
                session.save(this);
                transaction.commit();

                return true;
            } catch (Exception ex) {

                // Log the exception here
                transaction.rollback();

                return false;
            }
        } finally {
            HibernateUtil.closeSession();
        }
    }

    /**
     *
     * @return
     */
    public boolean delete() {
        final Session session = HibernateUtil.currentSession();

        try {
            final Transaction transaction = session.beginTransaction();

            try {
                session.delete(this);
                transaction.commit();

                return true;
            } catch (Exception ex) {

                // Log the exception here
                transaction.rollback();

                return false;
            }
        } finally {
            HibernateUtil.closeSession();
        }
    }

    /**
     *
     * @return
     */
    public boolean update() {
        final Session session = HibernateUtil.currentSession();

        try {
            final Transaction transaction = session.beginTransaction();

            try {
                session.merge(this);
                transaction.commit();

                return true;
            } catch (Exception ex) {

                // Log the exception here
                transaction.rollback();

                return false;
            }
        } finally {
            HibernateUtil.closeSession();
        }
    }
}



