package com.projetIF4.model;

//Generated 24 mars 2014 18:11:52 by Hibernate Tools 3.6.0

//~--- non-JDK imports --------------------------------------------------------

import com.projetIF4.hibernate.HibernateUtil;

import org.hibernate.Session;
import org.hibernate.Transaction;

//~--- JDK imports ------------------------------------------------------------

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Grade generated by hbm2java
 */
public class Grade implements java.io.Serializable {
    private Set     enseignants = new HashSet(0);
    private Integer codegra;
    private String  grade;

    /**
     *
     */
    public Grade() {}

    /**
     *
     * @param grade
     */
    public Grade(String grade) {
        this.grade = grade;
    }

    /**
     *
     * @param grade
     * @param enseignants
     */
    public Grade(String grade, Set enseignants) {
        this.grade       = grade;
        this.enseignants = enseignants;
    }

    /**
     *
     * @return
     */
    public Integer getCodegra() {
        return this.codegra;
    }

    /**
     *
     * @param codegra
     */
    public void setCodegra(Integer codegra) {
        this.codegra = codegra;
    }

    /**
     *
     * @return
     */
    public String getGrade() {
        return this.grade;
    }

    /**
     *
     * @param grade
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     *
     * @return
     */
    public Set getEnseignants() {
        return this.enseignants;
    }

    /**
     *
     * @param enseignants
     */
    public void setEnseignants(Set enseignants) {
        this.enseignants = enseignants;
    }

    @Override
    public int hashCode() {
        int hash = 7;

        hash = 97 * hash + Objects.hashCode(this.codegra);
        hash = 97 * hash + Objects.hashCode(this.grade);

        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        if (getClass() != obj.getClass()) {
            return false;
        }

        final Grade other = (Grade) obj;

        if (!Objects.equals(this.codegra, other.codegra)) {
            return false;
        }

        if (!Objects.equals(this.grade, other.grade)) {
            return false;
        }

        return true;
    }

    /**
     *
     * @return
     */
    public boolean save() {
        final Session session = HibernateUtil.currentSession();

        try {
            final Transaction transaction = session.beginTransaction();

            try {
                session.save(this);
                transaction.commit();

                return true;
            } catch (Exception ex) {

                // Log the exception here
                transaction.rollback();

                return false;
            }
        } finally {
            HibernateUtil.closeSession();
        }
    }

    /**
     *
     * @return
     */
    public boolean delete() {
        final Session session = HibernateUtil.currentSession();

        try {
            final Transaction transaction = session.beginTransaction();

            try {
                session.delete(this);
                transaction.commit();

                return true;
            } catch (Exception ex) {

                // Log the exception here
                transaction.rollback();

                return false;
            }
        } finally {
            HibernateUtil.closeSession();
        }
    }

    /**
     *
     * @return
     */
    public boolean update() {
        final Session session = HibernateUtil.currentSession();

        try {
            final Transaction transaction = session.beginTransaction();

            try {
                session.merge(this);
                transaction.commit();

                return true;
            } catch (Exception ex) {

                // Log the exception here
                transaction.rollback();

                return false;
            }
        } finally {
            HibernateUtil.closeSession();
        }
    }
}