package com.projetIF4.model;
// Generated 16 avr. 2014 11:44:49 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Notification generated by hbm2java
 */
public class Notification  implements java.io.Serializable {


     private Integer idNotif;
     private Utilisateur utilisateur;
     private String titre;
     private String message;
     private Date dateEnvoi;
     private String etat;
    /**
     *
     */

    public Notification() {
    }

    /**
     *
     * @param utilisateur
     * @param titre
     * @param message
     * @param dateEnvoi
     * @param etat
     */
    public Notification(Utilisateur utilisateur, String titre, String message, Date dateEnvoi, String etat) {
       this.utilisateur = utilisateur;
       this.titre = titre;
       this.message = message;
       this.dateEnvoi = dateEnvoi;
       this.etat = etat;
    }
   
    /**
     *
     * @return
     */
    public Integer getIdNotif() {
        return this.idNotif;
    }
    
    /**
     *
     * @param idNotif
     */
    public void setIdNotif(Integer idNotif) {
        this.idNotif = idNotif;
    }

    /**
     *
     * @return
     */
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    /**
     *
     * @param utilisateur
     */
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    /**
     *
     * @return
     */
    public String getTitre() {
        return this.titre;
    }
    
    /**
     *
     * @param titre
     */
    public void setTitre(String titre) {
        this.titre = titre;
    }

    /**
     *
     * @return
     */
    public String getMessage() {
        return this.message;
    }
    
    /**
     *
     * @param message
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     *
     * @return
     */
    public Date getDateEnvoi() {
        return this.dateEnvoi;
    }
    
    /**
     *
     * @param dateEnvoi
     */
    public void setDateEnvoi(Date dateEnvoi) {
        this.dateEnvoi = dateEnvoi;
    }

    /**
     *
     * @return
     */
    public String getEtat() {
        return this.etat;
    }
    
    /**
     *
     * @param etat
     */
    public void setEtat(String etat) {
        this.etat = etat;
    }




}


