package com.projetIF4.model;

//Generated 29 mars 2014 16:50:57 by Hibernate Tools 3.6.0
//~--- JDK imports ------------------------------------------------------------
import com.projetIF4.hibernate.HibernateUtil;
import java.util.Date;
import java.util.Objects;
import org.hibernate.CacheMode;
import org.hibernate.FlushMode;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Pfe generated by hbm2java
 */
public class Pfe implements java.io.Serializable {

    private Integer codepfe;
    private Specialite specialite;
    private Enseignant encadreur;
    private Enseignant chefjury;
    private Enseignant rapporteur;
    private Section section;
    private Salle salle;    
    private Etudiant etudiantByEtuCin1;
    private Etudiant etudiantByEtuCin;
    private String nomprojet;
    private String description;
    private Date datesoutenance;
    private String dureesoutenance;
    private String raisonSociale;
    private String responsablesociete;
    private String adressesociete;
    private Integer telsociete;
    private String encadrantsociete;
    private String fonctionencadrant;
    private String mailencadrant;
    private Integer telencadrant;
    private String methodeconception;
    private String langageprog;
    private String outilsprog;
    private Boolean remuneration;

    /**
     *
     */
    public Pfe() {
    }

    /**
     *
     * @param specialite
     * @param encadreur
     * @param chefjury
     * @param salle
     * @param rapporteur
     * @param etudiantByEtuCin1
     * @param etudiantByEtuCin
     * @param nomprojet
     * @param description
     * @param section
     * @param datesoutenance
     * @param duree
     * @param raisonSociale
     * @param responsablesociete
     * @param adressesociete
     * @param telsociete
     * @param encadrantsociete
     * @param fonctionencadrant
     * @param mailencadrant
     * @param telencadrant
     * @param methodeconception
     * @param langageprog
     * @param outilsprog
     * @param remuneration
     */
    public Pfe(Specialite specialite, Enseignant encadreur, Enseignant chefjury, Salle salle,
            Enseignant rapporteur, Etudiant etudiantByEtuCin1, Etudiant etudiantByEtuCin, String nomprojet,
            String description,Section section ,Date datesoutenance,String duree, String raisonSociale, String responsablesociete,
            String adressesociete, Integer telsociete, String encadrantsociete, String fonctionencadrant,
            String mailencadrant, Integer telencadrant, String methodeconception, String langageprog,
            String outilsprog, Boolean remuneration) {
        this.specialite = specialite;
        this.encadreur = encadreur;
        this.rapporteur = rapporteur;
        this.chefjury = chefjury;
        this.salle = salle;
        this.etudiantByEtuCin1 = etudiantByEtuCin1;
        this.etudiantByEtuCin = etudiantByEtuCin;
        this.nomprojet = nomprojet;
        this.description = description;
        this.datesoutenance = datesoutenance;
        this.dureesoutenance=duree;
        this.raisonSociale = raisonSociale;
        this.responsablesociete = responsablesociete;
        this.adressesociete = adressesociete;
        this.telsociete = telsociete;
        this.encadrantsociete = encadrantsociete;
        this.fonctionencadrant = fonctionencadrant;
        this.mailencadrant = mailencadrant;
        this.telencadrant = telencadrant;
        this.methodeconception = methodeconception;
        this.langageprog = langageprog;
        this.outilsprog = outilsprog;
        this.remuneration = remuneration;
        this.section=section;
    }

    @Override
    public int hashCode() {
        int hash = 3;

        hash = 47 * hash + Objects.hashCode(this.codepfe);
        hash = 47 * hash + Objects.hashCode(this.nomprojet);
        hash = 47 * hash + Objects.hashCode(this.description);
        hash = 47 * hash + Objects.hashCode(this.datesoutenance);
        hash = 47 * hash + Objects.hashCode(this.raisonSociale);
        hash = 47 * hash + Objects.hashCode(this.responsablesociete);
        hash = 47 * hash + Objects.hashCode(this.adressesociete);
        hash = 47 * hash + Objects.hashCode(this.telsociete);
        hash = 47 * hash + Objects.hashCode(this.encadrantsociete);
        hash = 47 * hash + Objects.hashCode(this.fonctionencadrant);
        hash = 47 * hash + Objects.hashCode(this.mailencadrant);
        hash = 47 * hash + Objects.hashCode(this.telencadrant);
        hash = 47 * hash + Objects.hashCode(this.methodeconception);
        hash = 47 * hash + Objects.hashCode(this.langageprog);
        hash = 47 * hash + Objects.hashCode(this.outilsprog);
        hash = 47 * hash + Objects.hashCode(this.remuneration);

        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        if (getClass() != obj.getClass()) {
            return false;
        }

        final Pfe other = (Pfe) obj;

        if (!Objects.equals(this.codepfe, other.codepfe)) {
            return false;
        }

        if (!Objects.equals(this.nomprojet, other.nomprojet)) {
            return false;
        }

        if (!Objects.equals(this.description, other.description)) {
            return false;
        }

        if (!Objects.equals(this.datesoutenance, other.datesoutenance)) {
            return false;
        }

        if (!Objects.equals(this.raisonSociale, other.raisonSociale)) {
            return false;
        }

        if (!Objects.equals(this.responsablesociete, other.responsablesociete)) {
            return false;
        }

        if (!Objects.equals(this.adressesociete, other.adressesociete)) {
            return false;
        }

        if (!Objects.equals(this.telsociete, other.telsociete)) {
            return false;
        }

        if (!Objects.equals(this.encadrantsociete, other.encadrantsociete)) {
            return false;
        }

        if (!Objects.equals(this.fonctionencadrant, other.fonctionencadrant)) {
            return false;
        }

        if (!Objects.equals(this.mailencadrant, other.mailencadrant)) {
            return false;
        }

        if (!Objects.equals(this.telencadrant, other.telencadrant)) {
            return false;
        }

        if (!Objects.equals(this.methodeconception, other.methodeconception)) {
            return false;
        }

        if (!Objects.equals(this.langageprog, other.langageprog)) {
            return false;
        }

        if (!Objects.equals(this.outilsprog, other.outilsprog)) {
            return false;
        }

        if (!Objects.equals(this.remuneration, other.remuneration)) {
            return false;
        }

        return true;
    }

    /**
     *
     * @return
     */
    public Enseignant getEncadreur() {
        return encadreur;
    }

    /**
     *
     * @param encadreur
     */
    public void setEncadreur(Enseignant encadreur) {
        this.encadreur = encadreur;
    }

    /**
     *
     * @return
     */
    public Enseignant getChefjury() {
        return chefjury;
    }

    /**
     *
     * @param chefjury
     */
    public void setChefjury(Enseignant chefjury) {
        this.chefjury = chefjury;
    }

    /**
     *
     * @return
     */
    public Enseignant getRapporteur() {
        return rapporteur;
    }

    /**
     *
     * @param rapporteur
     */
    public void setRapporteur(Enseignant rapporteur) {
        this.rapporteur = rapporteur;
    }

    /**
     *
     * @return
     */
    public String getDureesoutenance() {
        return dureesoutenance;
    }

    /**
     *
     * @param dureesoutenance
     */
    public void setDureesoutenance(String dureesoutenance) {
        this.dureesoutenance = dureesoutenance;
    }

    /**
     *
     * @return
     */
    public Section getSection() {
        return section;
    }

    /**
     *
     * @param section
     */
    public void setSection(Section section) {
        this.section = section;
    }

    /**
     *
     * @return
     */
    public Integer getCodepfe() {
        return this.codepfe;
    }

    /**
     *
     * @param codepfe
     */
    public void setCodepfe(Integer codepfe) {
        this.codepfe = codepfe;
    }

    /**
     *
     * @return
     */
    public Specialite getSpecialite() {
        return this.specialite;
    }

    /**
     *
     * @param specialite
     */
    public void setSpecialite(Specialite specialite) {
        this.specialite = specialite;
    }

    /**
     *
     * @return
     */
    public Salle getSalle() {
        return this.salle;
    }

    /**
     *
     * @param salle
     */
    public void setSalle(Salle salle) {
        this.salle = salle;
    }

    /**
     *
     * @return
     */
    public Etudiant getEtudiantByEtuCin1() {
        return this.etudiantByEtuCin1;
    }

    /**
     *
     * @param etudiantByEtuCin1
     */
    public void setEtudiantByEtuCin1(Etudiant etudiantByEtuCin1) {
        this.etudiantByEtuCin1 = etudiantByEtuCin1;
    }

    /**
     *
     * @return
     */
    public Etudiant getEtudiantByEtuCin() {
        return this.etudiantByEtuCin;
    }

    /**
     *
     * @param etudiantByEtuCin
     */
    public void setEtudiantByEtuCin(Etudiant etudiantByEtuCin) {
        this.etudiantByEtuCin = etudiantByEtuCin;
    }

    /**
     *
     * @return
     */
    public String getNomprojet() {
        return this.nomprojet;
    }

    /**
     *
     * @param nomprojet
     */
    public void setNomprojet(String nomprojet) {
        this.nomprojet = nomprojet;
    }

    /**
     *
     * @return
     */
    public String getDescription() {
        return this.description;
    }

    /**
     *
     * @param description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     *
     * @return
     */
    public Date getDatesoutenance() {
        return this.datesoutenance;
    }

    /**
     *
     * @param datesoutenance
     */
    public void setDatesoutenance(Date datesoutenance) {
        this.datesoutenance = datesoutenance;
    }

    /**
     *
     * @return
     */
    public String getRaisonSociale() {
        return this.raisonSociale;
    }

    /**
     *
     * @param raisonSociale
     */
    public void setRaisonSociale(String raisonSociale) {
        this.raisonSociale = raisonSociale;
    }

    /**
     *
     * @return
     */
    public String getResponsablesociete() {
        return this.responsablesociete;
    }

    /**
     *
     * @param responsablesociete
     */
    public void setResponsablesociete(String responsablesociete) {
        this.responsablesociete = responsablesociete;
    }

    /**
     *
     * @return
     */
    public String getAdressesociete() {
        return this.adressesociete;
    }

    /**
     *
     * @param adressesociete
     */
    public void setAdressesociete(String adressesociete) {
        this.adressesociete = adressesociete;
    }

    /**
     *
     * @return
     */
    public Integer getTelsociete() {
        return this.telsociete;
    }

    /**
     *
     * @param telsociete
     */
    public void setTelsociete(Integer telsociete) {
        this.telsociete = telsociete;
    }

    /**
     *
     * @return
     */
    public String getEncadrantsociete() {
        return this.encadrantsociete;
    }

    /**
     *
     * @param encadrantsociete
     */
    public void setEncadrantsociete(String encadrantsociete) {
        this.encadrantsociete = encadrantsociete;
    }

    /**
     *
     * @return
     */
    public String getFonctionencadrant() {
        return this.fonctionencadrant;
    }

    /**
     *
     * @param fonctionencadrant
     */
    public void setFonctionencadrant(String fonctionencadrant) {
        this.fonctionencadrant = fonctionencadrant;
    }

    /**
     *
     * @return
     */
    public String getMailencadrant() {
        return this.mailencadrant;
    }

    /**
     *
     * @param mailencadrant
     */
    public void setMailencadrant(String mailencadrant) {
        this.mailencadrant = mailencadrant;
    }

    /**
     *
     * @return
     */
    public Integer getTelencadrant() {
        return this.telencadrant;
    }

    /**
     *
     * @param telencadrant
     */
    public void setTelencadrant(Integer telencadrant) {
        this.telencadrant = telencadrant;
    }

    /**
     *
     * @return
     */
    public String getMethodeconception() {
        return this.methodeconception;
    }

    /**
     *
     * @param methodeconception
     */
    public void setMethodeconception(String methodeconception) {
        this.methodeconception = methodeconception;
    }

    /**
     *
     * @return
     */
    public String getLangageprog() {
        return this.langageprog;
    }

    /**
     *
     * @param langageprog
     */
    public void setLangageprog(String langageprog) {
        this.langageprog = langageprog;
    }

    /**
     *
     * @return
     */
    public String getOutilsprog() {
        return this.outilsprog;
    }

    /**
     *
     * @param outilsprog
     */
    public void setOutilsprog(String outilsprog) {
        this.outilsprog = outilsprog;
    }

    /**
     *
     * @return
     */
    public Boolean getRemuneration() {
        return this.remuneration;
    }

    /**
     *
     * @param remuneration
     */
    public void setRemuneration(Boolean remuneration) {
        this.remuneration = remuneration;
    }

    /**
     *
     * @return
     */
    public boolean update() {
        final Session session = HibernateUtil.currentSession();
        session.setFlushMode(FlushMode.COMMIT);
        session.setCacheMode(CacheMode.REFRESH);
        try {
            final Transaction transaction = session.beginTransaction();

            try {
                session.merge(this);
                transaction.commit();
                session.refresh(this);
                return true;
            } catch (HibernateException ex) {
                transaction.rollback();
                return false;
            }
        } finally {
            HibernateUtil.closeSession();
        }
    }
    public boolean save() {
        final Session session = HibernateUtil.currentSession();
        session.setFlushMode(FlushMode.COMMIT);
        session.setCacheMode(CacheMode.REFRESH);
        try {
            final Transaction transaction = session.beginTransaction();

            try {
                session.save(this);
                transaction.commit();
                session.refresh(this);
                return true;
            } catch (HibernateException ex) {
                transaction.rollback();
                return false;
            }
        } finally {
            HibernateUtil.closeSession();
        }
    }

}
